apiVersion: v2
name: demo-flask-app
description: A Helm chart for Demo Flask Application
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - flask
  - python
  - demo
maintainers:
  - name: banicr
home: https://github.com/banicr/demo-flask-app
